### ISSUE TITLE
怎么部署啊？

### ISSUE THREAD

**Issue by xdeng** [cshome/cshome#3]
怎么部署啊？没教程？没看到index.php

**Comment by wenmingtang** [comment]
参照 Symfony 的安装

开发预览部署步骤

1、clone 代码
2、composer install
3、php bin/console server:run 
4、访问 localhost:8000

**Comment by xdeng** [comment]
@wenmingtang 还是没懂  不是像其他php程序一样放到www目录建个数据库就行了吗

**Comment by wenmingtang** [comment]
@xdeng 没有那么容易哎 😔
